name: "Lighthouse"

on:
  workflow_dispatch:

jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - name: "☁️ checkout repository"
        uses: actions/checkout@v7

      - name: "🔧 setup node"
        uses: actions/setup-node@v7
        with:
          node-version: 21
          cache: "npm"

      - name: "🛳️ run Lighthouse CI"
        run: |
          npm install -g @lhci/cli@0.13.x
          lhci autorun --collect.numberOfRuns=1
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          LHCI_TOKEN: ${{ secrets.LHCI_TOKEN }}
